name: open_brewery_db
description: API wrapper for openbrewerydb.org
version: 0.0.1
homepage: https://github.com/claytonjacobs/open_brewery_db

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
